sqlq "INSERT INTO Customers (CustomerID, CompanyName, ContactName, Country) VALUES ('STUDE', 'Student Company', 'Mary Lebens', 'USA');"
sqlq "SELECT CustomerID, CompanyName FROM Customers Where CustomerID = 'STUDE';"
sqlq "INSERT INTO Orders (CustomerID, EmployeeID, OrderDate, ShipCountry) VALUES ('STUDE', 1, GETDATE(), 'USA');"
sqlq "SELECT TOP 1 OrderID FROM Orders WHERE CustomerID = 'STUDE' ORDER BY OrderID DESC;"
sqlq "UPDATE Customers SET ContactName = 'New Contact Name' WHERE CustomerID = 'STUDE';"
sqlq "SELECT ContactName FROM Customers WHERE CustomerID = 'STUDE';"
sqlq "UPDATE Orders SET ShipCountry = 'New Country' WHERE CustomerID = 'STUDE';"
sqlq "SELECT ShipCountry FROM Orders WHERE CustomerID = 'STUDE';"
sqlq "DELETE FROM Orders WHERE CustomerID = 'STUDE';"
sqlq "SELECT OrderID, CustomerID FROM Orders WHERE CustomerID = 'STUDE';"
sqlq "DELETE FROM Customers WHERE CustomerID = 'STUDE';"
sqlq "SELECT CustomerID, CompanyName FROM Customers WHERE CustomerID = 'STUDE';"
sqlq "INSERT INTO Suppliers (CompanyName, ContactName, ContactTitle, Country) VALUES ('Pop-up Foods', 'Duy Pham', 'Owner', 'Viet Nam');"
sqlq "SELECT * FROM Suppliers WHERE CompanyName = 'Pop-up Foods';"
sqlq "INSERT INTO Products (ProductName, SupplierID, CategoryID, UnitPrice, UnitsInStock) VALUES ('House Special Pizza', (SELECT SupplierID FROM Suppliers WHERE CompanyName = 'Pop-up Foods'), 2, 15.99, 50);"
sqlq "SELECT * FROM Products WHERE ProductName = 'House Special Pizza';"
sqlq "UPDATE Products SET UnitPrice = 16.99 WHERE ProductName = 'House Special Pizza';"
sqlq "SELECT * FROM Products WHERE ProductName = 'House Special Pizza';"
sqlq "UPDATE Products SET UnitsInStock = 25, UnitPrice = 17.99 WHERE ProductName = 'House Special Pizza';"
sqlq "SELECT * FROM Products WHERE ProductName = 'House Special Pizza';"
sqlq "DELETE FROM Products WHERE ProductName = 'House Special Pizza';"
sqlq "SELECT * FROM Products WHERE ProductName = 'House Special Pizza';"
